language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DIRECT_STATE=-direct OPT_STATE=-optimal
  - DIRECT_STATE=direct OPT_STATE=-optimal

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=2.7.12 DIRECT_STATE=direct OPT_STATE=-optimal
#    - os: osx
#      language: generic
#      env: PYTHON=3.5.6
#    - os: osx
#      language: generic
#      env: PYTHON=3.6.8

notifications:
  email: false

cache: pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$DIRECT_STATE" == "direct" ]]; then
    sudo apt-get install -y -qq python-dev gfortran build-essential ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update ;
    brew install openssl readline ;
    brew outdated pyenv || brew upgrade pyenv ;
    brew install pyenv-virtualenv ;
    pyenv install $PYTHON ;
    export PYENV_VERSION=$PYTHON ;
    export PATH="/Users/travis/.pyenv/shims:${PATH}" ;
    pyenv-virtualenv venv ;
    source venv/bin/activate ;
    python --version ;
    if [[ "$DIRECT_STATE == "direct" ]]; then
    brew install gfortran ;
    fi

install:
  - pip install -U pip
  - pip install numpy
  - pip install -e . -v

script: 
  - bash run_all_tests.sh sanity $DIRECT_STATE $OPT_STATE
