language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DIRECT_STATE=-direct OPT_STATE=-optimal
  - DIRECT_STATE=direct OPT_STATE=-optimal


# We have to be explicit with the OSX versions because Python is not supported by default.
# The Python versions then have to be explicitly labelled with full version numbers because
# that is what pyenv uses for the installs. The extra "python" label to fix the display in the UI.
matrix:
  include:
    - os: osx
      language: generic
      python: 2.7
      env: PYTHON=2.7.12 DIRECT_STATE=direct OPT_STATE=-optimal
    - os: osx
      language: generic
      python: 2.7
      env: PYTHON=2.7.12 DIRECT_STATE=-direct OPT_STATE=-optimal
    - os: osx
      language: generic
      python: 3.5
      env: PYTHON=3.5.6 DIRECT_STATE=direct OPT_STATE=-optimal
    - os: osx
      language: generic
      python: 3.5
      env: PYTHON=3.5.6 DIRECT_STATE=-direct OPT_STATE=-optimal
    - os: osx
      language: generic
      python: 3.6
      env: PYTHON=3.6.8 DIRECT_STATE=direct OPT_STATE=-optimal
    - os: osx
      language: generic
      python: 3.6
      env: PYTHON=3.6.8 DIRECT_STATE=-direct OPT_STATE=-optimal

notifications:
  email: false

before_cache:
  - brew cleanup

cache:
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.pyenv_cache

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$DIRECT_STATE" == "direct" ]]; then
    sudo apt-get install -y -qq python-dev gfortran build-essential ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update ;
    brew outdated pyenv || brew upgrade pyenv ;
    brew install pyenv-virtualenv ;
    pyenv install $PYTHON ;
    export PYENV_VERSION=$PYTHON ;
    export PATH="/Users/travis/.pyenv/shims:${PATH}" ;
    pyenv-virtualenv venv ;
    source venv/bin/activate ;
    python --version ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$DIRECT_STATE" == "direct" ]]; then
    brew install gcc ;
    fi

install:
  - pip install -U pip
  - pip install numpy
  - pip install -r requirements-dev.txt
  - pip install -e . -v

script: 
  - bash run_all_tests.sh sanity $DIRECT_STATE
  - bash run_all_tests.sh
