language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  #- DIRECT_STATE=-direct OPT_STATE=-optimal
  - DIRECT_STATE=direct OPT_STATE=-optimal

notifications:
  email: false

#cache: pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$DIRECT_STATE" == "direct" ]]; then
    sudo apt-get install -y -qq python-dev gfortran liblapack-dev libatlas-dev libblas-dev build-essential ;
    fi

install:
  - pip install -U pip
  - pip install numpy
  - pip install . -v
  - cd dragonfly/utils/direct_fortran/
  - python -c "import direct"

script: 
  - bash run_all_tests.sh sanity $DIRECT_STATE $OPT_STATE
