language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - INCLUDE_FORTRAN= INCLUDE_OPT=
  - INCLUDE_FORTRAN=fortran INCLUDE_OPT=

notifications:
  email: false

cache: pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && ! -z "$INCLUDE_FORTRAN" ]]; then
    sudo apt-get install -y -qq python-dev gfortran build-essential;
    fi

install:
  - pip install -U pip
  - pip install numpy
  - pip install .

script: 
  - bash run_all_tests.sh sanity $INCLUDE_FORTRAN $INCLUDE_OPT
